export enum RootGetters {
  UPDATE_VERSION = "UPDATE_VERSION",
  COUNTER_CHECK = "COUNTER_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
  USER_LISTS = "USER_LISTS",
}
export enum RootMutations {
  UPDATE_VERSION = "UPDATE_VERSION",
  COUNTER_CHECK = "COUNTER_CHECK",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
  USER_LISTS = "USER_LISTS",
}
export enum RootActions {
  UPDATE_VERSION = "UPDATE_VERSION",
  COUNTER_CHECK = "COUNTER_CHECK",
  USER_LISTS = "USER_LISTS",
}

export enum CounterGetters {
  COUNTER_VALUE = "COUNTER_VALUE",
  DOUBLED_COUNTER = "DOUBLED_COUNTER",
  GET_ROOT_DISPATCH = "GET_ROOT_DISPATCH",
}
export enum CounterMutations {
  SET_COUNTER = "SET_COUNTER",
  RESET_COUNTER = "RESET_COUNTER",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
}
export enum CounterActions {
  GET_COUNTER = "GET_COUNTER",
  CALL_COUNTER = "CALL_COUNTER",
  SET_ROOT_DISPATCH = "SET_ROOT_DISPATCH",
}
